In [2]:
import torch
import pandas as pd

# 创建示例Tensor并转为DataFrame
tensor = torch.randn(5, 3)
df = pd.DataFrame(tensor.numpy())

# 设置显示样式：隐藏行号、居中对齐、保留两位小数
styled_df = (
    df.style
    .format("{:.2f}")  # 所有列保留两位小数
    .hide(axis="index")  # 隐藏行索引
    .set_properties(**{'text-align': 'center'})  # 居中对齐
)

styled_df  # 在Jupyter Notebook中直接显示

In [6]:
import torch
a = torch.arange(0, 100, 2)
print(a)
b = torch.arange(0,100,2).float()
print(b)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])
tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
        28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 52., 54.,
        56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76., 78., 80., 82.,
        84., 86., 88., 90., 92., 94., 96., 98.])


In [9]:
import torch

a = torch.arange(0, 5,2)
print(a)
b = torch.arange(10,20,2)
print(b)

c = torch.outer(a,b)
print(c)


tensor([0, 2, 4])
tensor([10, 12, 14, 16, 18])
tensor([[ 0,  0,  0,  0,  0],
        [20, 24, 28, 32, 36],
        [40, 48, 56, 64, 72]])


In [13]:
a = torch.arange(0, 5,2).float()
print(a)

b = torch.ones_like(a)
print(b)


torch.polar(torch.ones_like(a), a)

tensor([0., 2., 4.])
tensor([1., 1., 1.])


tensor([ 1.0000+0.0000j, -0.4161+0.9093j, -0.6536-0.7568j])

In [15]:
import math

math.cos(2)
math.sin(2)

0.9092974268256817

In [16]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = torch.arange(10).float()
b = torch.arange(10).float()
print(a)
print(b)
torch.polar(a, b)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


tensor([ 0.0000+0.0000j,  0.5403+0.8415j, -0.8323+1.8186j, -2.9700+0.4234j,
        -2.6146-3.0272j,  1.4183-4.7946j,  5.7610-1.6765j,  5.2773+4.5989j,
        -1.1640+7.9149j, -8.2002+3.7091j])

In [25]:
2 * math.sin(2)
2 * math.cos(2)

-0.8322936730942848

In [33]:
x = torch.randn(5, 3, 4)
print(x)
print(x.shape)
print(*x.shape[:-1])
y = x.reshape(*x.shape[:-1], -1, 2)
print(y.shape)  # 将最后一个维度，按照两两组合一起

tensor([[[ 0.4828, -0.7157,  0.2841, -0.2611],
         [ 1.2683, -0.9698,  0.9873,  0.0608],
         [-1.1975,  0.4187,  0.5773, -0.0235]],

        [[-1.1678,  0.5373,  1.8520,  1.0601],
         [ 0.8407, -2.5092, -0.9872,  1.2944],
         [-2.1075, -0.6487, -1.6468,  0.1553]],

        [[-0.1607, -1.1331, -0.9364,  0.7902],
         [ 0.4609,  0.0084,  1.5581, -1.9579],
         [ 0.1918, -0.4210,  0.8150, -0.8730]],

        [[-1.0201,  0.2158,  1.1502,  0.0419],
         [ 0.0988,  1.3335, -1.3125, -1.3773],
         [ 1.0808, -0.2699,  1.0712,  1.3845]],

        [[ 0.5062,  1.1081, -0.5404, -0.5584],
         [ 0.3509,  0.0748, -1.1312, -0.3952],
         [ 0.5770, -0.5398, -0.4251, -0.3915]]])
torch.Size([5, 3, 4])
5 3
torch.Size([5, 3, 2, 2])


In [35]:
from torch import rsqrt


x = torch.randn(2,10)
print(x)
y = rsqrt(x.pow(2))
print(y)
z = torch.rsqrt(x.pow(2).mean(-1))
print(z)
z2 = torch.rsqrt(x.pow(2).mean(-1, keepdim=True))
print(z2)

tensor([[ 0.9176, -1.8937,  0.4263,  0.5140, -0.2966,  1.5288,  0.0998, -1.2622,
          1.1667, -0.5259],
        [-0.7966,  0.7539,  0.4374, -0.1496,  1.2094, -1.4577, -0.4989, -2.6800,
          0.1303,  0.8238]])
tensor([[ 1.0898,  0.5281,  2.3455,  1.9456,  3.3717,  0.6541, 10.0215,  0.7923,
          0.8571,  1.9015],
        [ 1.2553,  1.3264,  2.2864,  6.6846,  0.8269,  0.6860,  2.0044,  0.3731,
          7.6734,  1.2138]])
tensor([0.9740, 0.8727])
tensor([[0.9740],
        [0.8727]])


In [6]:
import torch
a = torch.randint(0, 10, (3, 4)).float()
print(a)
b = torch.ones_like(a)
print(b)
c = torch.randint_like(a, 0, 100)
print(c)

tensor([[9., 5., 1., 1.],
        [5., 2., 2., 0.],
        [1., 8., 0., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[12., 85., 50.,  2.],
        [63., 35., 74., 11.],
        [48., 55., 70., 22.]])
