# Torch 维度展开/缩小

unsqueeze 和 squeeze 方法
unsqueeze 需要指定维度dim

In [1]:
import torch


data = torch.tensor([1,2,3], dtype=torch.float32)
print(data.shape)



torch.Size([3])


In [2]:
# 在第0维加一个维度
zero_data = data.unsqueeze(0)
print(zero_data.shape)
print(zero_data)

torch.Size([1, 3])
tensor([[1., 2., 3.]])


In [3]:

# 在都一维加一个维度
one_data = data.unsqueeze(1)
print(one_data.shape)
one_data

torch.Size([3, 1])


tensor([[1.],
        [2.],
        [3.]])

In [4]:

remove_one = one_data.squeeze()
print(remove_one.shape)
print(remove_one)

torch.Size([3])
tensor([1., 2., 3.])


In [5]:
remove_one = zero_data.squeeze()
print(remove_one.shape)
print(remove_one)

torch.Size([3])
tensor([1., 2., 3.])


# 连接与堆叠
cat 和 stack堆叠

In [6]:
d = torch.tensor([1,2,3]).unsqueeze(dim=1)
print(d)
print(d.shape)

d_update = [d **i for i in range(1, 4)]
print(d_update)

d_update_cat_0 = torch.cat(d_update,dim = 0)
print(d_update_cat_0)
print(d_update_cat_0.shape)

d_update_dim_1 = torch.cat(d_update, dim = 1)
print(d_update_dim_1)
print(d_update_dim_1.shape)


tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])
[tensor([[1],
        [2],
        [3]]), tensor([[1],
        [4],
        [9]]), tensor([[ 1],
        [ 8],
        [27]])]
tensor([[ 1],
        [ 2],
        [ 3],
        [ 1],
        [ 4],
        [ 9],
        [ 1],
        [ 8],
        [27]])
torch.Size([9, 1])
tensor([[ 1,  1,  1],
        [ 2,  4,  8],
        [ 3,  9, 27]])
torch.Size([3, 3])


: 