In [1]:
import torch 

import torch.nn as nn


In [2]:
k = torch.rand(3,5)
k

tensor([[0.0614, 0.8415, 0.9287, 0.3447, 0.0035],
        [0.9626, 0.5218, 0.7776, 0.0698, 0.9172],
        [0.4020, 0.7778, 0.3272, 0.2693, 0.4586]])

In [3]:
k.T

tensor([[0.0614, 0.9626, 0.4020],
        [0.8415, 0.5218, 0.7778],
        [0.9287, 0.7776, 0.3272],
        [0.3447, 0.0698, 0.2693],
        [0.0035, 0.9172, 0.4586]])

In [5]:
def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)

print(k)
rotate_half((k))

tensor([[0.0614, 0.8415, 0.9287, 0.3447, 0.0035],
        [0.9626, 0.5218, 0.7776, 0.0698, 0.9172],
        [0.4020, 0.7778, 0.3272, 0.2693, 0.4586]])


tensor([[-0.9287, -0.3447, -0.0035,  0.0614,  0.8415],
        [-0.7776, -0.0698, -0.9172,  0.9626,  0.5218],
        [-0.3272, -0.2693, -0.4586,  0.4020,  0.7778]])